Team3_scheduling_app/config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/user' => 'users#index' # if user is admin, it will direct user to users/index page to see user info table
  
  get 'sessions/login' => 'sessions#login'
  
  get 'sessions/admin' => 'sessions#admin_login'
  
  get 'sessions/schedule' => 'schedules#index'
  
  get 'sessions/home' => 'sessions#home'

  get 'sessions/profile' => 'sessions#profile'

  get 'sessions/setting' => 'sessons#setting'

  get 'sessions/new' => 'sessions#new'

  get 'users/index'
  
  get 'schedules/list' => 'schedules#list'
  

  resources :schedules
  resources :machines
  resources :materials
  get    '/login',   to: 'sessions#login'
  post   '/login',   to: 'sessions#login_attempt'
  delete '/logout',  to: 'sessions#destroy'
  
  get    '/admin_login',   to: 'sessions#admin_login'
  post   '/admin_login',   to: 'sessions#admin_login_attempt'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :admins
  resources :users
  
  root 'users#new'
  

end

Team3_scheduling_app/app/models/machine.rb
class Machine < ActiveRecord::Base
end

Team3_scheduling_app/app/controllers/machines_controller.rb
class MachinesController < ApplicationController
    before_action :set_machine, only: [:show, :edit, :update, :destroy]
 
  def index
    @machines = Machine.all
  end

  
  def show
  end

  
  def new
    @machine = Machine.new
  end

  def edit
  end

  
  def create
    @machine = Machine.new(machine_params)

    respond_to do |format|
      if @machine.save
        format.html { redirect_to '/machines', notice: 'Machine was successfully created.' }
        format.json { render :show, status: :created, location: root }
      else
        format.html { render :new }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def update
    respond_to do |format|
      if @machine.update(machine_params)
        format.html { redirect_to @machine, notice: 'Machine was successfully updated.' }
        format.json { render :show, status: :ok, location: @machine }
      else
        format.html { render :edit }
        format.json { render json: @machine.errors, status: :unprocessable_entity }
      end
    end
  end

  
  def destroy
    @machine.destroy
    respond_to do |format|
      format.html { redirect_to machines_url, notice: 'Machine was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_machine
      @machine = Machine.find(params[:id])
    end

    def machine_params
      params.require(:machine).permit(:machineID, :machineDescription, :materialUsed)
    end
end

Team3_scheduling_app/app/helpers/machines_helper.rb
module MachinesHelper
end

Team3_scheduling_app/app/views/machines/_form.html.erb
<!--This form is for adding new machines to the machine-DB-->

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
<style>
@import url('https://fonts.googleapis.com/css?family=Titillium+Web');
</style>

<%= form_for(@machine) do |f| %>
  <% if @machine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@machine.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @machine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form">
    <!-- The newly created machine will be added to the machine database-->
    <!-- This will allow the user to select it when making a new reservation-->
    <h1>Add New Machine</h1>
      <div id="new_machine" style="display: block;">
          
        <div class="field-wrap">
          <label for="machine_machineID">Machine Name<span class="req">*</span></label>
          <input type="text" name="machine[machineID]" id="machine_machineID"
            required autocomplete="off">
        </div>
        
        <div class="field-wrap">
          <label for="machine_machineDescription">Machine Type<span class="req">*</span></label>
          <input type="text" name="machine[machineDescription]" id="machine_machineDescription"
            required autocomplete="off">
        </div>
        
        <div class="field-wrap">
          <label for="machine_materialUsed">Material Used<span class="req">*</span></label>
          <input type="text" name="machine[materialUsed]" id="machine_materialUsed"
            required autocomplete="off">
        </div>
        
        <button type="submit" class="button button-block" name="commit" value="Create Machine"/>
            Add New Machine
        </button>
          
        <a href="/machines">
            <button type="button" class="button button-small">Back</button>
        </a>
        
      </div> <!--/new_machine-->
    </form>
  </div> <!--/form-->

<!--Javascript-->
<script src='//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script>$('.form').find('input, textarea').on('keyup blur focus', function (e) {
  
  var $this = $(this),
      label = $this.prev('label');

	  if (e.type === 'keyup') {
			if ($this.val() === '') {
          label.removeClass('active highlight');
        } else {
          label.addClass('active highlight');
        }
    } else if (e.type === 'blur') {
    	if( $this.val() === '' ) {
    		label.removeClass('active highlight'); 
			} else {
		    label.removeClass('highlight');   
			}   
    } else if (e.type === 'focus') {
      
      if( $this.val() === '' ) {
    		label.removeClass('highlight'); 
			} 
      else if( $this.val() !== '' ) {
		    label.addClass('highlight');
			}
    }

});

</script>
<% end %>

Team3_scheduling_app/app/views/machines/edit.html.erb
<h1>Editing Machine</h1>

<%= render 'form' %>

<%= link_to 'Show', @machine %> |
<%= link_to 'Back', machines_path %>

Team3_scheduling_app/app/views/machines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Machines</h1>
<div class="btn-group btn-group-justified">
    <%= link_to 'New Machine', new_machine_path, class: "btn btn-lg btn-danger" %>
    <%= link_to 'Back', users_path, class: "text-center btn btn-lg btn-danger" %>
</div>

<table class="adminTable">
  <thead>
    <tr>
      <th>Machine ID</th>
      <th>Description</th>
      <th>Material</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody> 
   
    <% @machines.all.each do |machine| %>
      <tr>
        <td><%= machine.machineID %></td>
        <td><%= machine.machineDescription %></td>
        <td><%= machine.materialUsed %></td>
        <td><%= link_to 'Show', machine %></td>
        <td><%= link_to 'Edit', edit_machine_path(machine) %></td>
        <td><%= link_to 'Destroy', machine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

Team3_scheduling_app/app/views/machines/new.html.erb
<!--This page renders the add machine form-->

<%= render 'form' %>

Team3_scheduling_app/app/views/machines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Machine ID:</strong>
  <%= @machine.machineID %>
</p>

<p>
  <strong>Type:</strong>
  <%= @machine.machineDescription %>
</p>

<p>
  <strong>Material:</strong>
  <%= @machine.materialUsed %>
</p>

<%= link_to 'Edit', edit_machine_path(@machine) %> |
<%= link_to 'Back', machines_path %>