Team3_scheduling_app/config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/user' => 'users#index' # if user is admin, it will direct user to users/index page to see user info table
  
  get 'sessions/login' => 'sessions#login'
  
  get 'sessions/admin' => 'sessions#admin_login'
  
  get 'sessions/schedule' => 'schedules#index'
  
  get 'sessions/home' => 'sessions#home'

  get 'sessions/profile' => 'sessions#profile'

  get 'sessions/setting' => 'sessons#setting'

  get 'sessions/new' => 'sessions#new'

  get 'users/index'
  
  get 'schedules/list' => 'schedules#list'
  

  resources :schedules
  resources :machines
  resources :materials
  get    '/login',   to: 'sessions#login'
  post   '/login',   to: 'sessions#login_attempt'
  delete '/logout',  to: 'sessions#destroy'
  
  get    '/admin_login',   to: 'sessions#admin_login'
  post   '/admin_login',   to: 'sessions#admin_login_attempt'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :admins
  resources :users
  
  root 'users#new'
  

end

Team3_scheduling_app/app/models/schedule.rb
class Schedule < ActiveRecord::Base
end

Team3_scheduling_app/app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
    before_action :set_schedule, only: [:show, :edit, :update, :destroy]
 
  def index
    @schedules = Schedule.all
  end

  def list
    @schedules = Schedule.all
  end
  
  
  def show
  end

  def new
    @schedule = Schedule.new
  end

  def edit
  end

 
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to schedules_url, notice: 'Schedule entry was successfully created.' }
        format.json { render :show, status: :created, location: root }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end


 
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_list_url, notice: 'Schedule entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    def schedule_params
      params.require(:schedule).permit(:machineID, :userName, :startTime, :endTime)
    end
end

Team3_scheduling_app/app/helpers/schedules_helper.rb
module SchedulesHelper
end

Team3_scheduling_app/app/views/schedules/_form.html.erb
<!--This page is used to create a new reservations-->

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">

<style>
@import url('https://fonts.googleapis.com/css?family=Titillium+Web');
</style>
  
<%= form_for(@schedule) do |f| %>

<div class="form">
  <h1>Create a Reservation</h1>
  
  <div class="field-wrap">
    <label class="active" for="schedule_machineID">Machine </label>
    <!-- when a new machine is added to the system, it will be added to the list of machines users can chose from -->
    <%= f.select(:machineID, Machine.all.pluck(:machineID)) %>
  </div>
  
  <div class="field-wrap">
    <label class="active" for="schedule_userName">Username</label>
    <input type="text" name="schedule[userName]" id="schedule_userName" 
    required autocomplete="off"/>
  </div>
  
  <div class="field-wrap">
      <div class='input-group date' id='datetimepicker6'>
        <label class="active" for="schedule_startTime">Please select starting date and time</label>
        <input type='text' class="form-control" name="schedule[startTime]"
        id= "schedule_startTime" placeholder="Select start time"/>
        
        <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
        </span>
      </div>
  </div>

  <div class="field-wrap">
      <div class='input-group date' id='datetimepicker7'>
        <label class="active" for="schedule_endTime">Please select same date with an end time</label>
        <input type='text' class="form-control" name="schedule[endTime]"
        id= "schedule_endTime" placeholder="Select end time"/>
        
        <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
        </span>
      </div>
  </div>

  <button type="submit" class="button button-block" name="commit"/>
      Reserve Time
  </button>
      
  <!--Error messages-->
  <% if @schedule.errors.any? %>
      <div class="animated shake" id="error_explanation">
        <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>
  
        <ul>
        <% @schedule.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
  <a href="/schedules">
      <button type="button" class="button button-small">Back</button>
  </a>
      
    </div> <!--/signup-->
  </form>
</div> <!--/form-->
  
  <!--Javascript and options set for bootstrap dateTimepicker-->
<script type="text/javascript">
  $(function () {
    $('#datetimepicker6').datetimepicker({
      sideBySide: true,
      useCurrent: true,
      showClear: true,
      format:'MMM DD, YYYY h:mmaZ',
      stepping: 30
    });
    $('#datetimepicker7').datetimepicker({
      sideBySide: true,
      useCurrent: false, //Important! See issue #107
      showClear: true,
      format:'MMM DD, YYYY h:mmaZ',
      stepping: 30
        
    });
    $("#datetimepicker6").on("dp.change", function (e) {
        $('#datetimepicker7').data("DateTimePicker").minDate(e.date);
        
    });
    $("#datetimepicker7").on("dp.change", function (e) {
        $('#datetimepicker6').data("DateTimePicker").maxDate(e.date);
    });
  });
</script>
<% end %>

Team3_scheduling_app/app/views/schedules/_form2.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>Enter your username in the reserved field to make a reservation.</p>
  <div class="field">
    <%= f.label :machineID %><br>
    <%= f.select :machineID, ['Machine 1', 'Machine 2', 'Machine 3', 'Machine 4'] %>
  </div>
  
  <div class="field">
    <%= f.label :userName %><br>
    <%= f.text_field :userName %>
  </div>
  
  <div class="field">
    <%= f.label :startTime %><br>
    <%= f.text_field :startTime %>
  </div>
  <div class="field">
    <%= f.label :endTime %><br>
    <%= f.text_field :endTime %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Team3_scheduling_app/app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |

Team3_scheduling_app/app/views/schedules/index.html.erb
<!--This page displays all reservation made by users-->

<h1 class="title"><b>CaMS Maker Lab Schedule</b></h1>

<div class="btn-group btn-group-justified">
    <%= link_to "New Schedule", new_schedule_path, class: "btn btn-lg btn-danger" %>
    <%= link_to "Log out", "/", class: "text-center btn btn-lg btn-danger" %>
</div>

<div id="dashboard">
    <div id="control"></div>
    <div id="lab_schedule"></div>
</div>      

       
<script src='//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script src="https://www.google.com/jsapi?key=ABCDE"></script>
<script type="text/javascript">

    
    //Reloads the page to fix issue of the google timeline not showing upupon
    //first load
    function LoadGoogle()
    {
        if(typeof google != 'undefined' && google && google.load)
        {
          google.load('visualization', '1', {packages: ['controls'], callback: drawChart});  
          google.setOnLoadCallback(drawChart);
        }
        else
        {
            // Retry later...
            setTimeout(LoadGoogle, 100);
        }
    }

    LoadGoogle();
    
    // Create the data table.
    function drawChart() {
      var data = new google.visualization.DataTable();
          data.addColumn({type: 'string', id: 'MachineID'});
          data.addColumn({type: 'string', id: 'userName'});
          data.addColumn({type: 'date', id: 'startTime'});
          data.addColumn({type:'date', id: 'endTime'});
          
          data.addRows([
          <% @schedules.each do |sched| %>
            ['<%= sched.machineID%>', '<%= sched.userName %>',
            new Date('<%= sched.startTime %>'),
            new Date('<%= sched.endTime %>')],
            <% end %>
      ]);
     
    var chart = new google.visualization.ChartWrapper({
        chartType: 'Timeline',
        containerId: 'lab_schedule',
        options: {
            height: 450,
            hAxis: {
                
              format: 'MM/dd/yy h:mma'
            },
            vAxis: 
            {
                gridlines : {count:6, color:'#B9B9B9'},
                minorGridLines : { count:5} 
            }
        }
    });
      var control = new google.visualization.ControlWrapper({
        controlType: 'ChartRangeFilter',
        containerId: 'control',
        options: {
            filterColumnIndex: 3, // filter on start date
            ui: {
                chartOptions: {
                    height: 50
                },
                chartView: {
                    columns: [3, {
                        // create en empty column to serve as the line series in the control
                        // since there is no real meaning to having a line in here
                        type: 'number',
                        calc: function () {return 0;}
                    }]
                }
            }
        }
        
    });
    
    //draws data on the google chart
    var dashboard = new google.visualization.Dashboard(document.querySelector('#dashboard'));
        dashboard.bind([control], [chart]);
        dashboard.draw(data);
    }
</script>

Team3_scheduling_app/app/views/schedules/list.html.erb
<!--<p id="notice"><%= notice %></p>-->

<h1>Schedules List</h1>
<div class="btn-lg">
    <%= link_to 'Back', users_path, class: "text-center btn btn-lg btn-danger" %>
</div>

<table class="adminTable">
  <thead>
    <tr>
      <th>Machine</th>
      <th>User</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |sched| %>
      <tr>
        <td><%= sched.machineID %></td>
        <td><%= sched.userName %></td>
        <td><%= sched.startTime %></td>
        <td><%= sched.endTime %></td>
        <td><%= link_to 'Destroy', sched, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

Team3_scheduling_app/app/views/schedules/new.html.erb
<!--This page loads in the new reservation page and refreshes the page once-->
<body onLoad="LoadOnce">

<%= render 'form' %>

<!-- app/views/users/new.html.erb -->

<!--
<h1>Signup!</h1>

<%= form_for :schedule, url: '/schedules' do |f| %>


<% end %>
-->
</body>
<script type='text/javascript'>

(function()
{
  if( window.localStorage )
  {
    if( !localStorage.getItem( 'firstLoad' ) )
    {
      localStorage[ 'firstLoad' ] = true;
      window.location.reload();
    }  
    else
      localStorage.removeItem( 'firstLoad' );
  }
})();

</script>

Team3_scheduling_app/app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Machine:</strong>
  <%= @schedule.machine %>
</p>

<p>
  <strong>Type:</strong>
  <%= @schedule.machine_type %>
</p>

<p>
  <strong>Time Block:</strong>
  <%= @schedule.timeBlock %>
</p>

<p>
  <strong>Reserved:</strong>
  <%= @schedule.reserved %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>