Team3_scheduling_app/config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/user' => 'users#index' # if user is admin, it will direct user to users/index page to see user info table
  
  get 'sessions/login' => 'sessions#login'
  
  get 'sessions/admin' => 'sessions#admin_login'
  
  get 'sessions/schedule' => 'schedules#index'
  
  get 'sessions/home' => 'sessions#home'

  get 'sessions/profile' => 'sessions#profile'

  get 'sessions/setting' => 'sessons#setting'

  get 'sessions/new' => 'sessions#new'

  get 'users/index'
  
  get 'schedules/list' => 'schedules#list'
  

  resources :schedules
  resources :machines
  resources :materials
  get    '/login',   to: 'sessions#login'
  post   '/login',   to: 'sessions#login_attempt'
  delete '/logout',  to: 'sessions#destroy'
  
  get    '/admin_login',   to: 'sessions#admin_login'
  post   '/admin_login',   to: 'sessions#admin_login_attempt'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :admins
  resources :users
  
  root 'users#new'
  

end

Team3_scheduling_app/app/models/user.rb
class User < ActiveRecord::Base
  EMAIL_REGEX = /\A\S+@.+\.\S+\z/
  # allows: letters (capital and lowercase) numbers, dashes and underscores.
  USER_REGEX = /\A[\w-]+\z/
  # must be at least 6 characters and include one number and one letter.
  PW_REGEX = /\A(?=.*[a-zA-Z])(?=.*[0-9]).{3,}\z/
  
  #user must enter user name
  validates :userName, :presence => true, :uniqueness => true, :format => USER_REGEX
  validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
  validates :password, :presence => true, :format => PW_REGEX
  
  before_save :encrypt_password
  after_save :clear_password

  
  def encrypt_password
    return if persisted? && password == User.find(id).password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.password= BCrypt::Engine.hash_secret(password, salt)
    end
  end
  def clear_password
    self.password = nil
  end
  def clear_username
    self.userName = nil
  end
  
  #verifys that the entered username and password match an user entry in the database table
  def self.authenticate(username_or_email="", login_password="")
    if  EMAIL_REGEX.match(username_or_email)    
      user = User.find_by_email(username_or_email)
    else
      user = User.find_by_userName(username_or_email)
    end
    if user && user.match_password(login_password)
      return user
    else
      return false
    end
  end
  
  #checks the password by hashing the entered plain text password with the salt value
  def match_password(login_password="")
    password == BCrypt::Engine.hash_secret(login_password, salt)
  end
    
    
end

Team3_scheduling_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  
  
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to '/', notice: 'User was successfully created. Wait for approval.' }
        format.json { render :show, status: :created, location: root }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:userName, :email, :password, :approval, :admin)
    end
end

Team3_scheduling_app/app/helpers/users_helper.rb
module UsersHelper
end

Team3_scheduling_app/app/views/users/_form.html.erb
<!--This page is used to edit user infomation.-->

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">

<style>
@import url('https://fonts.googleapis.com/css?family=Titillium+Web');
</style>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form">
    <h1>Editing User</h1>
    
    <div class="field-wrap">
      <%= f.label :userName, :class => 'active' %>
      <%= f.text_field :userName %>
    </div>
    
    <div class="field-wrap">
      <%= f.label :email, :class => 'active' %>
      <%= f.text_field :email %>
    </div>
    
    <div class="field-wrap">
      <%= f.label :password, :class => 'active' %>
      <%= f.text_field :password %>
    </div>
    
    <div class="field-wrap">
      <%= f.label :approval, :class => 'active' %>
      <!--false/true switch used to determine whether or not the user is allowed to make a reservation -->
      <!--By default, when a new user is created, the switch is false -->
      <!--users must wait for the admin to set approval to true in order to log in and make a reservation -->
      <%= f.select :approval, ['false','true'] %>
    </div>
    
    <div class="field-wrap">
      <%= f.label :admin, :class => 'active' %>
      <!--false/true switch used to determine whether or not the user has admin privileges -->
      <%= f.select :admin, ['false','true'] %>
    </div>
    
    <button type="submit" class="button button-block" name="commit"/>
        Submit
    </button>
        
  </div> <!--/form-->
  
  <!--Javascript-->
  <script src='//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <script>$('.form').find('input, textarea').on('keyup blur focus', function (e) {
  
  var $this = $(this),
      label = $this.prev('label');

	  if (e.type === 'keyup') {
			if ($this.val() === '') {
          label.removeClass('active highlight');
        } else {
          label.addClass('active highlight');
        }
    } else if (e.type === 'blur') {
    	if( $this.val() === '' ) {
    		label.removeClass('active highlight'); 
			} else {
		    label.removeClass('highlight');   
			}   
    } else if (e.type === 'focus') {
      
      if( $this.val() === '' ) {
    		label.removeClass('highlight'); 
			} 
      else if( $this.val() !== '' ) {
		    label.addClass('highlight');
			}
    }

});

$('.tab a').on('click', function (e) {
  
  e.preventDefault();
  
  $(this).parent().addClass('active');
  $(this).parent().siblings().removeClass('active');
  
  target = $(this).attr('href');

  $('.tab-content > div').not(target).hide();
  
  $(target).fadeIn(600);
  
});</script>
<% end %>

Team3_scheduling_app/app/views/users/edit.html.erb
<!--This page renders the edit user page-->

<%= render 'form' %>

<div class="btn-group btn-lg">
  <%= link_to 'Back', users_path, class: "text-center btn btn-lg btn-danger" %>
  <%= link_to 'Show', @user, class: "text-center btn btn-lg btn-danger" %>
</div>

Team3_scheduling_app/app/views/users/index.html.erb
<!--This is the Administrator Tools page for approving new users and adding new 
machines. Once an admin logs in this the page they will see-->

<h1 class= "title"><b>Listing Users</b></h1>

<div class="btn-group btn-group-justified">
    <%= link_to 'New User', new_user_path, class: "btn btn-lg btn-danger" %>
    <%= link_to 'Show Machines', machines_path, class: "text-center btn btn-lg btn-danger" %>
    <%= link_to 'Show Schedule List', schedules_list_path, class: "btn btn-lg btn-danger" %>
    <%= link_to 'Log Out', root_path, class: "text-center btn btn-lg btn-danger" %>
</div>

<table class="adminTable">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Password</th>
      <th>Approval</th>
      <th>Administrator</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.userName %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.approval %></td>
        <td><%= user.admin %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

Team3_scheduling_app/app/views/users/new.html.erb
<!--This page is used to sign up a new user-->

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">

<style>
@import url('https://fonts.googleapis.com/css?family=Titillium+Web');
</style>

<%= form_for(@user) do |f| %>

  
  <div class="form">
    <h1>Sign Up for CaMS Maker Lab</h1>
    <ul class="tab-group">
      <li class="tab active"><a href="#signup">Sign Up</a></li>
      <li class="tab"><a href="/sessions/new">Log In</a></li>
    </ul>
    
    <div class="tab-content">
      <form action="/" method="post">
        <div id="signup" style="display: block;">

            
          <div class="field-wrap">
            <label for="user_userName">Username<span class="req">*</span></label>
            <input type="text" name="user[userName]" id="user_userName"
              required autocomplete="off">
          </div>
          
          <div class="field-wrap">
            <label for="user_email">Email<span class="req">*</span></label>
            <input type="email" name="user[email]" id="user_email"
              required autocomplete="off">
          </div>
          
          <div class="field-wrap">
            <label for="user_password">Password<span class="req">*</span></label>
            <input type="password" name="user[password]" id="user_password"
              required autocomplete="off">
          </div>
          
          <button type="submit" class="button button-block" name="commit"/>
              Get Approved
          </button>
          
          <!--Error messages-->
          <% if @user.errors.any? %>
              <div class="animated shake" id="error_explanation">
                <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
          
                <ul>
                <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
            
          <a href="/">
              <button type="button" class="button button-small">Back</button>
          </a>
          
        </div> <!--/signup-->
      </form>
    </div> <!--/tab-content-->
  </div> <!--/form-->
  
  <!--Javascript-->
<script src='//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
<script>$('.form').find('input, textarea').on('keyup blur focus', function (e) {
  
  var $this = $(this),
      label = $this.prev('label');

	  if (e.type === 'keyup') {
			if ($this.val() === '') {
          label.removeClass('active highlight');
        } else {
          label.addClass('active highlight');
        }
    } else if (e.type === 'blur') {
    	if( $this.val() === '' ) {
    		label.removeClass('active highlight'); 
			} else {
		    label.removeClass('highlight');   
			}   
    } else if (e.type === 'focus') {
      
      if( $this.val() === '' ) {
    		label.removeClass('highlight'); 
			} 
      else if( $this.val() !== '' ) {
		    label.addClass('highlight');
			}
    }

});

</script>
<% end %>

Team3_scheduling_app/app/views/users/recoveryform.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :userName %><br>
    <%= f.text_field :userName %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :training %><br>
    <%= f.text_field :training %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Team3_scheduling_app/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="showInfo">

  <p>
    <strong>Username:</strong>
    <%= @user.userName %>
  </p>
  
  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>
  
  <p>
    <strong>Password:</strong>
    <%= @user.password %>
  </p>
  
  <p>
    <strong>Approval:</strong>
    <%= @user.approval %>
  </p>
  
  <p>
    <strong>Admin Status:</strong>
    <%= @user.admin %>
  </p>
</div>

<div class="btn-group btn-lg">
  <%= link_to 'Edit', edit_user_path(@user), class: "text-center btn btn-lg btn-danger" %>
  <%= link_to 'Back', users_path, class: "text-center btn btn-lg btn-danger" %>
</div>